APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:WJGeyNthT1135Y4hzNDEY63B1Md58sCRfK7eKvGHmcs=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=sirux
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=pusher


PUSHER_APP_PATH=localhost

TWILIO_AUTH_SID="ACce5621a59bab66533c5ff7210d34fc24"
TWILIO_AUTH_TOKEN="504104c386f8852ea837369315f44396"

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

MEMCACHED_HOST=localhost

REDIS_HOST=localhost
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=c.fernando.ventura.marin@gmail.com
MAIL_PASSWORD=kibyorihnuncoazt
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=c.fernando.ventura.marin@gmail.com
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

PUSHER_APP_ID=1711636
PUSHER_APP_KEY=c31a19ba809c5d332b89
PUSHER_APP_SECRET=df5e4569272e5a978ba7
PUSHER_HOST=localhost
PUSHER_PORT=443
PUSHER_SCHEME=https
PUSHER_APP_CLUSTER=us2

VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
VITE_PUSHER_HOST="${PUSHER_HOST}"
VITE_PUSHER_PORT="${PUSHER_PORT}"
VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
JWT_SECRET=O1aVmWdRlWZ5lUGU0TDjyL9TM685UgmjJ4hHgMN5TQBGWaRDO8v1U2NGcGxOF1Oa
